# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /bot

# Copy entire bot directory
COPY bot/ ./
RUN pip install --no-cache-dir -r requirements.txt

# Run the bot script
CMD ["python", "news_bot.py"]
